name: freshstart
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  drift: ^2.16.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.20
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  drift_dev: ^2.16.0

flutter:
  uses-material-design: true

